name: API Tests

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout My Tests
        uses: actions/checkout@v4

      - name: Checkout FreeAPI Backend
        uses: actions/checkout@v4
        with:
          repository: hiteshchoudhary/apihub
          path: freeapi-backend

      - name: Start FreeAPI
        run: |
          cd freeapi-backend
          echo MONGODB_URI=mongodb://mongodb:27017 > .env
          echo PORT=8080 >> .env
          echo NODE_ENV=development >> .env
          echo ACCESS_TOKEN_SECRET=super_secret_access_token_key_1234567890 >> .env
          echo ACCESS_TOKEN_EXPIRY=1d >> .env
          echo REFRESH_TOKEN_SECRET=super_secret_refresh_token_key_0987654321 >> .env
          echo REFRESH_TOKEN_EXPIRY=10d >> .env
          echo EXPRESS_SESSION_SECRET=session_secret_key >> .env
          echo CORS_ORIGIN=* >> .env
          
          sudo chmod -R 777 .
          docker compose up -d
          echo "Waiting for services to start..."
          sleep 90
          docker compose logs backend | tail -n 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest --alluredir=allure-results
        continue-on-error: true
        env:
          BASE_URL: http://localhost:8080/api/v1
          DB_URL: mongodb://localhost:27017/
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SERVICE_USERNAME: ${{ secrets.SERVICE_USERNAME }}
          SERVICE_PASSWORD: ${{ secrets.SERVICE_PASSWORD }}
          SERVICE_EMAIL: ${{ secrets.SERVICE_EMAIL }}

      - name: Install Latest Allure CLI via NPM
        if: always()
        run: |
          sudo npm install -g allure-commandline@latest --unsafe-perm=true
          allure --version
      - name: Generate Mono Allure Report
        if: always()
        run: |
          allure generate allure-results --clean --single-file -o allure-report
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report
          force_orphan: true