name: API Tests

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout My Tests
        uses: actions/checkout@v4

      - name: Checkout FreeAPI Backend
        uses: actions/checkout@v4
        with:
          repository: hiteshchoudhary/apihub
          path: freeapi-backend

      - name: Start FreeAPI
        run: |
          cd freeapi-backend
          # Чистая запись без внешних кавычек
          echo MONGODB_URI=mongodb://mongodb:27017 > .env
          echo PORT=8080 >> .env
          echo NODE_ENV=development >> .env
          echo ACCESS_TOKEN_SECRET=super_secret_access_token_key_1234567890 >> .env
          echo ACCESS_TOKEN_EXPIRY=1d >> .env
          echo REFRESH_TOKEN_SECRET=super_secret_refresh_token_key_0987654321 >> .env
          echo REFRESH_TOKEN_EXPIRY=10d >> .env
          echo EXPRESS_SESSION_SECRET=session_secret_key >> .env
          echo CORS_ORIGIN=* >> .env
          
          sudo chmod -R 777 .
          docker compose up -d
          echo "Waiting for services to start..."
          sleep 90
          docker compose logs backend | tail -n 20

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest --alluredir=allure-results
        continue-on-error: true
        env:
          BASE_URL: http://localhost:8080/api/v1
          DB_URL: mongodb://localhost:27017/
          USERNAME: test_user
          PASSWORD: strongPass123
          SERVICE_USERNAME: service_user
          SERVICE_PASSWORD: strongPass123
          SERVICE_EMAIL: secret@test.com

      - name: Get Allure history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report Action
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-history